/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;

import static Tampilan.Report.noPembelianReport;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import javax.swing.JOptionPane;

public class Buy1 extends javax.swing.JFrame {
    Connection con = null;
    Statement st = null;
    
    public Buy1() {
        initComponents();
        isi();
    }

    public void isi(){
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/gettick", "root", "");
            Statement st = con.createStatement();
            String simpan = "SELECT MAX(RIGHT(NoPembelian,5)) AS no_auto FROM pembeliant1";
            ResultSet rs = st.executeQuery(simpan);
            
            if(rs.next()){
                String no_auto, nol_plus;
                int p;
                no_auto=Integer.toString(rs.getInt(1));
                p = no_auto.length();
                nol_plus="";
                for (int i = 1; i <=5-p; i++) {
                    nol_plus = nol_plus+"0";
                }
                noPembelian.setText("GTPR"+nol_plus+no_auto);
            } 
            
            String sql = "SELECT * FROM pembeliant1 WHERE NoPembelian='"+noPembelian.getText()+"'";
            Statement st1 = con.createStatement();
            ResultSet rs1 = st1.executeQuery(sql);
            
            while(rs1.next()){
                idEvent.setText(rs1.getString("IDTiket"));
                namaEvent.setText(rs1.getString("NamaEvent"));
                nama.setText(rs1.getString("NamaLengkap"));
                email.setText(rs1.getString("Email"));
                noTelp.setText(rs1.getString("NoTelp"));
                hargaTiket.setText(rs1.getString("Harga"));
                jumlah.setText(rs1.getString("Jumlah"));
                metodeBayar.setText(rs1.getString("MetodeBayar"));
                totalBayar.setText(rs1.getString("Total"));
            }
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "GAGAL!");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        noPembelian = new javax.swing.JTextField();
        metodeBayar = new javax.swing.JTextField();
        idEvent = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        totalBayar = new javax.swing.JTextField();
        noTelp = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        namaEvent = new javax.swing.JTextField();
        hargaTiket = new javax.swing.JTextField();
        backButton = new javax.swing.JLabel();
        payButton = new javax.swing.JLabel();
        cancelButton = new javax.swing.JLabel();
        editButton = new javax.swing.JLabel();
        bgPay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GETTICK");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noPembelian.setEditable(false);
        noPembelian.setBackground(new java.awt.Color(255, 255, 255));
        noPembelian.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        noPembelian.setForeground(new java.awt.Color(10, 76, 134));
        noPembelian.setBorder(null);
        jPanel1.add(noPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 310, 40));

        metodeBayar.setEditable(false);
        metodeBayar.setBackground(new java.awt.Color(255, 255, 255));
        metodeBayar.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        metodeBayar.setForeground(new java.awt.Color(10, 76, 134));
        metodeBayar.setBorder(null);
        jPanel1.add(metodeBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 310, 40));

        idEvent.setEditable(false);
        idEvent.setBackground(new java.awt.Color(255, 255, 255));
        idEvent.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        idEvent.setForeground(new java.awt.Color(10, 76, 134));
        idEvent.setBorder(null);
        jPanel1.add(idEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 310, 30));

        jumlah.setEditable(false);
        jumlah.setBackground(new java.awt.Color(255, 255, 255));
        jumlah.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jumlah.setForeground(new java.awt.Color(10, 76, 134));
        jumlah.setBorder(null);
        jPanel1.add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 90, 40));

        totalBayar.setEditable(false);
        totalBayar.setBackground(new java.awt.Color(255, 255, 255));
        totalBayar.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        totalBayar.setForeground(new java.awt.Color(10, 76, 134));
        totalBayar.setBorder(null);
        jPanel1.add(totalBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 310, 40));

        noTelp.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        noTelp.setForeground(new java.awt.Color(10, 76, 134));
        noTelp.setBorder(null);
        jPanel1.add(noTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 310, 30));

        email.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        email.setForeground(new java.awt.Color(10, 76, 134));
        email.setBorder(null);
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 310, 40));

        nama.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        nama.setForeground(new java.awt.Color(10, 76, 134));
        nama.setBorder(null);
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 310, 40));

        namaEvent.setEditable(false);
        namaEvent.setBackground(new java.awt.Color(255, 255, 255));
        namaEvent.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        namaEvent.setForeground(new java.awt.Color(10, 76, 134));
        namaEvent.setBorder(null);
        jPanel1.add(namaEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 310, 40));

        hargaTiket.setEditable(false);
        hargaTiket.setBackground(new java.awt.Color(255, 255, 255));
        hargaTiket.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        hargaTiket.setForeground(new java.awt.Color(10, 76, 134));
        hargaTiket.setBorder(null);
        jPanel1.add(hargaTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 160, 40));

        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 50));

        payButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payButtonMouseClicked(evt);
            }
        });
        jPanel1.add(payButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 580, 110, 50));

        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 580, 110, 50));

        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonMouseClicked(evt);
            }
        });
        jPanel1.add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 580, 110, 50));

        bgPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/bgPay.png"))); // NOI18N
        jPanel1.add(bgPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void editButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseClicked
        String namaBaru = nama.getText();
        String emailBaru = email.getText();
        String noTelpBaru = noTelp.getText();
        
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/gettick", "root", "");
            Statement st = con.createStatement();
            String update = "UPDATE pembeliant1 SET NamaLengkap='"+namaBaru+"',Email='"+emailBaru+
                    "',NoTelp='"+noTelpBaru+"' WHERE NoPembelian='"+noPembelian.getText()+"'";
            String update2 = "UPDATE allbuy SET NamaLengkap='"+namaBaru+"',Email='"+emailBaru+
                    "',NoTelp='"+noTelpBaru+"' WHERE NoPembelian='"+noPembelian.getText()+"'";
            st.executeUpdate(update);
            st.executeUpdate(update2);
            JOptionPane.showMessageDialog(null, "Data Telah Ter-edit");
            isi();
        } catch(SQLException e){
           JOptionPane.showMessageDialog(null, "Edit Gagal");
        }
    }//GEN-LAST:event_editButtonMouseClicked

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        delete();
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void payButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payButtonMouseClicked
        noPembelianReport.setText(""+noPembelian.getText());
        Report rp = new Report();
        rp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_payButtonMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        delete();
    }//GEN-LAST:event_backButtonMouseClicked

    private void delete(){
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/gettick", "root", "");
            Statement st = con.createStatement();
            String cancel ="DELETE FROM pembeliant1 WHERE NoPembelian='"+noPembelian.getText() +"'";
            String cancel2 ="DELETE FROM allbuy WHERE NoPembelian='"+noPembelian.getText() +"'";
            st.executeUpdate(cancel);
            st.executeUpdate(cancel2);
            
            DetailBuyEvent1 cncl = new DetailBuyEvent1();
            cncl.setVisible(true);
            this.setVisible(false);
        } catch(SQLException e){
           JOptionPane.showMessageDialog(null, "Error");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buy1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buy1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buy1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buy1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buy1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backButton;
    private javax.swing.JLabel bgPay;
    private javax.swing.JLabel cancelButton;
    private javax.swing.JLabel editButton;
    private javax.swing.JTextField email;
    private javax.swing.JTextField hargaTiket;
    private javax.swing.JTextField idEvent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField metodeBayar;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField namaEvent;
    private javax.swing.JTextField noPembelian;
    private javax.swing.JTextField noTelp;
    private javax.swing.JLabel payButton;
    private javax.swing.JTextField totalBayar;
    // End of variables declaration//GEN-END:variables
}
