/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Register extends javax.swing.JFrame {
    Connection con = null;
    Statement st = null;
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }
    
    private void hapuslayar(){
        usernameField.setText("");
        nameField.setText("");
        pw1Field.setText("");
        pw2Field.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        pw1Field = new javax.swing.JPasswordField();
        pw2Field = new javax.swing.JPasswordField();
        createButton = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GETTICK");
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nameField.setBorder(null);
        nameField.setPreferredSize(new java.awt.Dimension(2, 14));
        jPanel1.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 240, 20));

        usernameField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        usernameField.setBorder(null);
        jPanel1.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 240, 20));

        pw1Field.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pw1Field.setBorder(null);
        pw1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pw1FieldActionPerformed(evt);
            }
        });
        jPanel1.add(pw1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 240, 30));

        pw2Field.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pw2Field.setBorder(null);
        pw2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pw2FieldActionPerformed(evt);
            }
        });
        jPanel1.add(pw2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 240, 20));

        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonMouseClicked(evt);
            }
        });
        jPanel1.add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 70, 40));

        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 70, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/bgRegistrasi.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pw1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pw1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pw1FieldActionPerformed

    private void pw2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pw2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pw2FieldActionPerformed

    private void createButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseClicked
        // TODO add your handling code here:
        try{
            if(usernameField.getText().equals("")||pw1Field.getPassword().equals("")||
                nameField.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Data ga bioleh kosong", "Pesan", JOptionPane.ERROR_MESSAGE);
                hapuslayar();
            } else if(!pw1Field.getText().contains(pw2Field.getText())){
                  JOptionPane.showMessageDialog(null, "Retype The Password Again");
                  hapuslayar();
                }else{
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    con = DriverManager.getConnection("jdbc:mysql://localhost/gettick", "root", "");
                    st = con.createStatement();
                    String simpan = "insert into tblogin values ('" + usernameField.getText() + "','" + 
                            String.valueOf(pw1Field.getPassword()) + "','" + nameField.getText() + "')";
                    st = con.createStatement();
                    int SA = st.executeUpdate(simpan);
                    JOptionPane.showMessageDialog(null, "Regis done");
                    this.setVisible(false);
                    new OnboardingAndLogin(null, true).setVisible(true);
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Akun ada!", "Pesan", JOptionPane.WARNING_MESSAGE);
            hapuslayar();
        }
    }//GEN-LAST:event_createButtonMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        OnboardingAndLogin login = new OnboardingAndLogin();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backButton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel createButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameField;
    private javax.swing.JPasswordField pw1Field;
    private javax.swing.JPasswordField pw2Field;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
